<?php
require_once __DIR__ . '/../src/Model/Database.php';
$pdo = Database::pdo();
// Fetch pages that look like posts (we'll pick the three main ones created earlier)
$slugs = ['el-origen-de-total-darkness','filosofia-modular-videojuegos','diagnostico-tecnico-cultural'];
$items = [];
// Try to collect project-based pages first (generated by generate_blog_from_projects.php)
// Try to populate items from contenido.txt (look for 'Proyectos destacados')
$items = [];
$contenidoPath = __DIR__ . '/../../contenido.txt';
if (file_exists($contenidoPath)) {
    $raw = file_get_contents($contenidoPath);
    $pos = mb_strpos($raw, 'Proyectos destacados');
    if ($pos !== false) {
        $sub = mb_substr($raw, $pos);
        // Split into blocks separated by two or more newlines
        $blocks = preg_split('/\r?\n\s*\r?\n+/', $sub);
        // first block is the heading line; drop it
        array_shift($blocks);
        // dynamic provisional media: prefer images from media/images/parallax if available
        $provisionalMedia = [];
        $parallaxDir = __DIR__ . '/../../media/images/parallax';
        if (is_dir($parallaxDir)) {
            $exts = ['png','jpg','jpeg','svg','gif','webp'];
            foreach ($exts as $ext) {
                foreach (glob($parallaxDir . '/*.' . $ext) as $f) {
                    $name = basename($f);
                    $provisionalMedia[] = '/media/images/parallax/' . $name;
                }
            }
        }
        if (empty($provisionalMedia)) {
            // fallback static list
            $provisionalMedia = ['/media/LogoXlerion.png','/media/LogoX.svg','/media/LogoXlerion.png','/media/MikeProfile.jpg'];
        }
        $mi = 0;
        foreach ($blocks as $b) {
            $b = trim($b);
            if ($b === '') continue;
            // Expect format: Title: description
            $parts = explode(':', $b, 2);
            if (count($parts) < 2) continue;
            $title = trim($parts[0]);
            $excerpt = trim($parts[1]);
            if ($title === '') continue;
            $items[] = ['title' => $title, 'slug' => slugify($title), 'excerpt' => $excerpt, 'image' => $provisionalMedia[$mi % count($provisionalMedia)]];
            $mi++;
        }
    }
}

// If we didn't find entries in contenido.txt, continue to project-based discovery
$projectDir = __DIR__ . '/../../xlerion_ultimate_web/XlerionStoryCreator';
// helper slugify (same as project generator)
function slugify($s) {
    $s = mb_strtolower($s);
    $s = preg_replace('/[\s_]+/u', '-', $s);
    $s = preg_replace('/[^a-z0-9\-]+/u', '', iconv('UTF-8', 'ASCII//TRANSLIT', $s));
    $s = preg_replace('/-+/','-',$s);
    return trim($s, '-');
}

// collect candidate slugs from project JSON files when available
$candidateSlugs = [];
if (is_dir($projectDir)) {
    foreach (glob($projectDir . '/*.json') as $f) {
        $raw = @file_get_contents($f);
        $data = @json_decode($raw, true);
        $title = $data['name'] ?? ($data['title'] ?? basename($f, '.json'));
        $candidateSlugs[] = $data['slug'] ?? slugify($title);
    }
}

// If no project JSONs found, fall back to a small set of known slugs
if (empty($candidateSlugs)) {
    $candidateSlugs = ['el-origen-de-total-darkness','filosofia-modular-videojuegos','diagnostico-tecnico-cultural'];
}
// Query cms_pages for candidate slugs (prefer project-generated pages); also include any pages with meta indicating 'projects'
$inQuery = implode(',', array_fill(0, count($candidateSlugs), '?'));
$st = $pdo->prepare('SELECT title,slug,content,meta FROM cms_pages WHERE slug IN (' . $inQuery . ') OR meta LIKE ? ORDER BY created_at DESC');
$params = $candidateSlugs;
$params[] = '%"generated_from":"projects"%';
$st->execute($params);
$rows = $st->fetchAll(PDO::FETCH_ASSOC);
foreach ($rows as $r) {
    // create excerpt from first paragraph
    if (preg_match('/<p>(.*?)<\/p>/is', $r['content'], $m)) { $excerpt = strip_tags($m[1]); } else { $excerpt = substr(strip_tags($r['content']),0,220); }
    $items[] = ['title'=>$r['title'],'slug'=>$r['slug'],'excerpt'=>$excerpt];
}

// Build HTML index
$html = '<div class="container my-4 blog-index-wrapper">'
    .'<div style="background:#ff4d4d;color:#fff;padding:0.9rem;border-radius:8px;margin-bottom:1rem;text-align:center;font-weight:700;">*** CAMBIO VISIBLE: contenido actualizado - haz Ctrl+F5 o abre 127.0.0.1:8080/blog?cb=1 para refrescar ***</div>'
    .'<div class="blog-search mb-4">'
    .'<input type="search" id="blogIndexSearch" class="form-control form-control-lg" placeholder="Buscar en entradas..." aria-label="Buscar entradas" />'
    .'</div>'
    .'<h1 class="mb-3">Blog</h1>'
    .'<div class="row g-3">';
foreach ($items as $it) {
    $html .= '<div class="col-12 col-md-6 col-lg-4 blog-card-wrap">';
    // attach provisional image if available (media folder)
    $imgTag = '';
    if (!empty($it['image'])) {
        $img = $it['image'];
        $imgTag = '<img loading="lazy" src="' . htmlspecialchars($img) . '" class="card-img-top" style="height:160px;object-fit:cover;" alt="' . htmlspecialchars($it['title']) . '" />';
    }
    $html .= '<article class="card h-100 blog-card" role="article" style="background:#ffe9b3;">';
    $html .= $imgTag;
    $html .= '<div class="card-body d-flex flex-column">';
    $html .= '<h5 class="card-title mb-1">' . htmlspecialchars($it['title']) . '</h5>';
    $html .= '<p class="card-text text-muted small flex-grow-1" style="min-height:3.6em;">' . htmlspecialchars($it['excerpt']) . '</p>';
    $html .= '<div class="d-flex justify-content-between align-items-center">';
    $html .= '<div class="small text-muted">Artículo</div>';
    $html .= '<div><a href="/blog/' . htmlspecialchars($it['slug']) . '" class="stretched-link-wrapper" aria-label="Abrir entrada"></a></div>';
    $html .= '</div></div></article></div>';
}
// client-side filtering script injected inline
$html .= '</div>'
    .'<script>(function(){var q=document.getElementById("blogIndexSearch");if(!q)return;var cards=[].slice.call(document.querySelectorAll(".blog-card-wrap"));q.addEventListener("input",function(){var v=q.value.toLowerCase();cards.forEach(function(c){var txt=c.textContent.toLowerCase();c.style.display=!v||txt.indexOf(v)!==-1?"":"none";});});})();</script>'
    .'</div>';

// Update blog page content
$u = $pdo->prepare('UPDATE cms_pages SET content = ?, meta = ? WHERE slug = ?');
$meta = json_encode(['generated_index'=>true,'generated_at'=>date('c')]);
$u->execute([$html,$meta,'blog']);
echo "Blog index populated\n";
